AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
