# syntax=docker/dockerfile:1.7

ARG RUBY_VERSION=3.4.4
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y bash build-essential curl git libjemalloc2 libpq-dev libvips libyaml-dev pkg-config postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

COPY Gemfile Gemfile.lock worker.gemspec ./
COPY lib ./lib

RUN --mount=type=cache,target=/usr/local/bundle/cache \
    bundle install

CMD ["bash"]
