# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in worker.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"
gem "bunny", "~> 2.24"
gem "pg", "~> 1.5"
gem "aws-sdk-s3", "~> 1.169"
gem "rubyzip", "~> 2.4"
gem "csv", "~> 3.3"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"
