apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamgate.fullname" . }}-worker
  labels:
    {{- include "streamgate.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streamgate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "streamgate.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "streamgate.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "streamgate.fullname" . }}-config
            - secretRef:
                name: {{ include "streamgate.fullname" . }}-runtime
          readinessProbe:
            exec:
              command: ["ruby", "-e", "exit 0"]
            periodSeconds: 20
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["ruby", "-e", "exit 0"]
            periodSeconds: 60
            failureThreshold: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
