{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "streamgate.fullname" . }}-runtime
  labels:
    {{- include "streamgate.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "streamgate.fullname" . }}-runtime
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.databaseUrl }}
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.redisUrl }}
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.rabbitmqUrl }}
    - secretKey: RAILS_MASTER_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.railsMasterKey }}
    - secretKey: STREAMGATE_WORKER_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.workerToken }}
    - secretKey: STREAMGATE_S3_BUCKET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.s3Bucket }}
    - secretKey: CLICKHOUSE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.clickhouseUrl }}
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.googleOAuthClientId }}
{{- end }}
