{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "streamgate.fullname" . }}
  labels:
    {{- include "streamgate.labels" . | nindent 4 }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: ["api", "web"]
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
