apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamgate.fullname" . }}-web
  labels:
    {{- include "streamgate.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "streamgate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
